menu:
  Home: /
  About: /about
  Projects: /projects
  Archives: /archives

widgets:
- recent_posts
- contact
- tagcloud

excerpt_link: Read More

twitter:
  username: lakenen
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: false

google_analytics: UA-20116272-1
rss:

comment_provider: disqus
