menu:
  Home: /blog
  Archives: /blog/archives

widgets:
- search
- recent_posts
- contact
- tagcloud

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-20116272-1
rss:

comment_provider: disqus
